### ISSUE TITLE
[BUG] Pulling bespoke scala deb from unvetted location

### ISSUE THREAD

**Issue by ToddG** [cluster-apps-on-docker/spark-standalone-cluster-on-docker#73]
## Bug

I mentioned this in [65](https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker/issues/65), but downloading the scala .deb from a random location is really unusual and will prevent me from both using and suggesting others use this project.

### Expected behaviour

I'd expect that scala be either pulled from a vetted location, pulled in as a vetted base image, or built from source using `sbt`.

### Current behaviour

```
build/docker/base/Dockerfile:    curl https://downloads.lightbend.com/scala/${scala_version}/scala-${scala_version}.deb -k -o scala.deb && \
```
* I do not know who or what lightbend.com is
* I see no reason to trust an arbitrary binary being pulled from this location

### Steps to reproduce

1. *Step 1*
Clone this repo

2. *Step 2*
```
cd ./build
```
3. *Step 3*

```
build.sh
```

### Possible solutions (optional)

* Use standard scala tooling to generate the scala binary

https://www.scala-sbt.org/sbt-native-packager/introduction.html

### Comments (optional)

*Add some comments, if any*

### Checklist

Please provide the following:

- [ ] Docker Engine version: 20.10.1
- [ ] Docker Compose version: 1.25.0

```
 $ git pretty | head
*   d908cb6 Merge pull request #72 from cluster-apps-on-docker/staging
```

**Comment by andre-marcos-perez** [comment]
Hi @ToddG, this is not a random location at all, it is the same server used by Scala lang on its official web page. Please, check it out here: https://www.scala-lang.org/download/.

In this sense, it is not different than the way we download Spark from https://archive.apache.org/dist/spark/.

Do you agree?

**Comment by ToddG** [comment]
Ok, cool. I did not realize that. I'm a little concerned that there are no hashes present to confirm the download...but that's a separate issue for the scala community. I'll close this ticket.

**Comment by andre-marcos-perez** [comment]
Hi, @ToddG your tip on hashes to validate the download is great. I will definitely add it on the backlog for the next release! Thanks for your contribution.
