### ISSUE TITLE
unable to connect to kafka from jupyter lab container but able to connect from spark-master container shell

### ISSUE THREAD

**Issue by papasanimohansrinivas** [cluster-apps-on-docker/spark-standalone-cluster-on-docker#79]
## Introduction

Hi there, thanks for helping the project! We are doing our best to help the community to learn and practice
parallel computing in distributed environments through our projects. :sparkles:

## Bug

Hi so i built  all the dockers from scratch  with help of build.sh and littel modifying the jupyterlab docker (by removing that c.notebook="" line).

After upping the containers so i have changed the spark-defaults.conf.template to spark-defualts.conf in spark-master conf folder and added kafka dependency to the conf file 

### Expected behaviour

Actually we should be able to connect to kafka broker when running code from pyspark jupyterlab container 

### Current behaviour

when running pyspark code from jupyterlab 
It is throwing this error 

AnalysisException: Failed to find data source: kafka. Please deploy the application as per the deployment section of "Structured Streaming + Kafka Integration Guide".;

But when running the code to connect to a kafka broker from pyspark terminal from spark-master it doesnot 

### Checklist

Please provide the following:

- [x] Docker Engine version: *Can be found using `docker version`, e.g.: 19.03.6*
- [x] Docker Compose version: *Can be found using `docker-compose version`, e.g.: 1.29.0*

**Comment by papasanimohansrinivas** [comment]
sorry i forgot to add kafka dependencies in sparksession while buidling it 
great work from ur side thanks again

**Comment by andre-marcos-perez** [comment]
Hi @papasanimohansrinivas, glad you solved it! If you need anything else, let me know. Please consider starring the project, it helps a lot.
